# Generated by Django 3.1 on 2023-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
    ]
