# Generated by Django 3.1 on 2023-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230311_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.IntegerField(blank=True, default=111111, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='xlsx_files', verbose_name='Файл'),
        ),
    ]
