# Generated by Django 3.1 on 2023-03-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230313_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
