# Generated by Django 3.1 on 2023-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('file', models.FileField(blank=True, null=True, upload_to='xlsx_files', verbose_name='Файл')),
            ],
        ),
    ]
