# Generated by Django 3.1 on 2023-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=255, verbose_name='Артикул'),
        ),
    ]
